name: Pulsar Manager Release

on:
  push:
    branches:
      - release/pm

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build
        run: |
          version=`cat VERSION`
          git checkout master
          ./gradlew clean distTar
          cd front-end
          npm install --save
          npm run build:prod
          cd ../
          mkdir -p temp-release temp-release/pulsar-manager
          cd temp-release
          cp ../distribution/LICENSE.bin.txt pulsar-manager/LICENSE
          cp ../distribution/NOTICE.bin.txt pulsar-manager/NOTICE
          cp -r ../distribution/licenses pulsar-manager/
          cp -r ../build/distributions/pulsar-manager.tar ../front-end/dist pulsar-manager
          tar -czvf apache-pulsar-manager-${version}-bin.tar.gz pulsar-manager
          mv apache-pulsar-manager-${version}-bin.tar.gz ../
          git checkout release/pm

      - name: publish code to github
        run: |
          ls -a
          echo $(pwd)
          docker build -f scripts/Dockerfile -t sn-pulsar-manager .
          docker run -e ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} -e GITHUB_REPOSITORY=streamnative/pulsar-manager -v $(pwd):/sn-pm sn-pulsar-manager sh -c 'upload-script.sh /sn-pm/apache-pulsar-manager-*'
